name: Wind Data Logger  

on:  
  schedule:  
    - cron: '50 06 * * *'  # Exécute à 12h UTC chaque jour  
    - cron: '15 12 * * *'  # Exécute à 16h UTC chaque jour  
    - cron: '50 18 * * *'  # Exécute à 20h UTC chaque jour  

  workflow_dispatch:  # Permet de lancer le script manuellement  

jobs:  
  run-script:  
    runs-on: ubuntu-latest  

    permissions:
      contents: write  # Ajout des permissions d'écriture

    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  

      - name: Setup Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.10'  

      - name: Install dependencies  
        run: pip install requests pandas  

      - name: Run script  
        run: python prt2.py  

      - name: Configure Git user identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Force Git to track changes  
        run: |
          git add -f wind_data.csv
          git commit -m "Mise à jour forcée des données de vent" || echo "Aucune modification à enregistrer"
          git push origin main

      - name: Check if the file is modified
        run: |
          git status
          ls -l wind_data.csv  # Voir la taille du fichier après l’exécution
          cat wind_data.csv     # Affiche les 5 premières lignes pour voir si les données sont là
